In [1]:
import pandas as pd
import numpy as np
from nltk import word_tokenize
from nltk.stem.snowball import SnowballStemmer
import time
import string

In [2]:
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier

In [3]:
from tools.parsers import generalinquirer as generalInquirerParser
from tools.parsers import largemoviereviews as largeMovieReviewsParser
from tools.parsers import generalinquirer as generalInquirerParser
from tools.parsers import negation as negationParser 

from tools.sentimentanalysis import preparation
from nltk.util import ngrams
from nltk import pos_tag, pos_tag_sents

In [4]:
maxWords = 25
onlyMpqa = False
doSave = False

In [5]:
stemmer = SnowballStemmer("english")
prepData = preparation.Preparation()
parserInquirer = generalInquirerParser.GeneralInquirer()
parserNegation = negationParser.Negation()
parserMovieReviews = largeMovieReviewsParser.LargeMovieReviews()

In [6]:
sentimentDictionary  = parserInquirer.readFileCsv(parserInquirer.combinedFileLoc)
sentencesMpqa = parserInquirer.readFileCsv(prepData.defaultFileNameSentimentSentencesNormalized)
negations = parserNegation.readFileCsv(parserNegation.defaultFileNameProcessed)
sentencesImdb = parserMovieReviews.readFileCsv(parserMovieReviews.defaultFileNameProcessed)
expectedResultsImdb = parserMovieReviews.readFileCsv(parserMovieReviews.defaultFileNameProcessedOverall)

In [7]:
non_english_text = ['im_401b_e73i32c22_031705-2', 'IZ-060316-01-Trans-1', '20000815_AFP_ARB.0084.IBM-HA-NEW', 'NapierDianne']
polarizedSentencesMpqa = sentencesMpqa[sentencesMpqa['sentiment-type'] == 0]
polarizedSentencesMpqa = polarizedSentencesMpqa[np.invert(polarizedSentencesMpqa['docName'].isin(non_english_text))]
polarizedSentencesMpqa.loc[polarizedSentencesMpqa.index, 'textRaw'] = polarizedSentencesMpqa.loc[polarizedSentencesMpqa.index, 'text']
polarizedSentencesMpqa.loc[polarizedSentencesMpqa.index, 'textLower'] = polarizedSentencesMpqa.loc[polarizedSentencesMpqa.index, 'text'].map( lambda cell: cell.lower())

sentimentDictionary['entryRaw'] = sentimentDictionary['entry']
sentimentDictionary['entry'] = sentimentDictionary['entry'].map(lambda cell: stemmer.stem(cell))

negations['phraseStemmed'] = negations['phrase'].map(lambda cell: stemmer.stem(cell).lower())

sentencesImdb = sentencesImdb[np.invert(sentencesImdb['id'].isnull())]
sentencesImdb = sentencesImdb[np.invert(sentencesImdb['text'].isnull())] 
sentencesImdb['textRaw'] = sentencesImdb['text'] 

In [8]:
def duplicate_attributes_directory(directory):
    checkCategories = ['positiv', 'negativ', 'active', 'passive', 'affil', 'hostile', 'strong',
                       'power', 'weak', 'submit', 'yes', 'no',
                       'negate', 'intrj', 'pleasur', 'pain', 'feel', 'need', 'persist']
    # copy categories among duplicate words in dictionary
    idx = 0
    while idx < directory.shape[0] - 1:
        found = {}
        for key in checkCategories:
            found[key] = directory[key][idx] == key

        idx2 = idx + 1
        while idx2 < directory.shape[0]:
            if directory['entry'][idx] == directory['entry'][idx2]:
                for key in checkCategories:
                    if directory[key][idx2] == key:
                        found[key] = True
                idx2 += 1
            else:
                idx2 -= 1
                break

        if idx2 == idx:
            idx += 1
        else:
            idx2 += 1
            for key in checkCategories:
                if found[key] != False:
                    directory[key][idx:idx2] = key

            idx = idx2 + 1
    return directory

In [9]:
pd.set_option('display.max_columns', 500)
sentimentDictionary = duplicate_attributes_directory(sentimentDictionary)

In [10]:
sentimentDictionary.drop_duplicates(subset = 'entry', inplace = True)
sentimentDictionary.shape

(2736, 26)

In [11]:
def infoDf(df, col):
    print("Negative: {}".format(df[df[col] < 0].shape))
    print("Neutral: {}".format(df[df[col] == 0].shape))
    print("Positive: {}".format(df[df[col] > 0].shape))

In [12]:
print("MPQA")
infoDf(polarizedSentencesMpqa, 'sentiment-intensity')
print
print("IMDB")
infoDf(sentencesImdb, 'type')

MPQA
Negative: (3131, 14)
Neutral: (1472, 14)
Positive: (2978, 14)

IMDB
Negative: (273487, 6)
Neutral: (0, 6)
Positive: (258804, 6)


In [13]:
def remove_articles(row):
    tokens = row['textArrStemmed']
    articles = ['a', 'an', 'the']
    tokens = [w for w in tokens if w not in articles]
    row['tokens'] = tokens
    return row

In [14]:
def get_punctuation(row):
    last_character = row['text'][-1:]
    if last_character in '?!.':
        row['punctuation'] = ord(last_character)
    else:
        if last_character in '"\'':
            penultimate_character = row['text'][-2:-1]
            if penultimate_character in '?!.':
                row['punctuation'] = ord(penultimate_character)
            else:
                row['punctuation'] = None
        else:
            row['punctuation'] = ord('x')

    return row

In [15]:
tStart = time.time()
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row: get_punctuation(row), axis = 1)
tEnd = time.time()
print("Timed MPQA data: {}".format(str(tEnd - tStart)))
# prepare movie reviews data
if not onlyMpqa:
    tStart = time.time()
    sentencesImdb = sentencesImdb.apply(lambda row: get_punctuation(row), axis = 1) 
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed MPQA data: 11.8000001907
Timed IMDB: 289.480999947


In [16]:
polarizedSentencesMpqa = polarizedSentencesMpqa[polarizedSentencesMpqa['punctuation'].notnull()]

In [17]:
polarizedSentencesMpqa.shape

(7865, 15)

In [18]:
def cleanUpWord(w):
    return w.translate(None, string.punctuation).strip()

In [19]:
def processWordsMpqa(row):
    global stemmer

    words = [ word for word in [cleanUpWord(w) for w in word_tokenize(row['textLower'])] if len(word) > 0]
    row['text'] = '|' + '|'.join(words) + '|'
    row['wordCount'] = len(words)
    row['textArr'] = words
    
    wordsStemmed = [stemmer.stem(unicode(w, errors='ignore')) for w in words]
    row['textStemmed'] = '|'.join(wordsStemmed)
    row['textStemmed'] = '|' + row['textStemmed'] + '|'
    row['textArrStemmed'] = wordsStemmed
    return row

def processWordsMovies(row):
    global stemmer

    words = [ word for word in [cleanUpWord(w) for w in row['text'].split('|')] if len(word) > 0]    
    wordsStemmed = [stemmer.stem(unicode(w, errors='ignore')) for w in words]
    row['textStemmed'] = '|'.join(wordsStemmed).lower()
    row['textStemmed'] = '|' + row['textStemmed'] + '|'
    row['wordCount'] = len(words)
    row['textArr'] = words
    row['textArrStemmed'] = wordsStemmed
    row['text'] = '|' + row['text'] + '|'
    return row

In [20]:
tStart = time.time()
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row: processWordsMpqa(row), axis = 1)
tEnd = time.time()
print("Timed MPQA data: {}".format(str(tEnd - tStart)))

Timed MPQA data: 19.373000145


In [21]:
polarizedSentencesMpqa = polarizedSentencesMpqa[polarizedSentencesMpqa['wordCount'] < maxWords]

In [22]:
tStart = time.time()
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row: remove_articles(row), axis = 1)
tEnd = time.time()
print("Timed MPQA data: {}".format(str(tEnd - tStart)))

Timed MPQA data: 2.50500011444


In [23]:
def generate_row_id(row):
    row['real-id'] = "{}#{}#{}".format(int(row['id']), int(row['rating']), int(row['set']))
    return row

In [24]:
# prepare movie reviews data
if not onlyMpqa:
    sentencesImdb = sentencesImdb.apply(lambda row: generate_row_id(row), axis = 1) 
    expectedResultsImdb = expectedResultsImdb.apply(lambda row: generate_row_id(row), axis = 1)

In [25]:
def equal_cuts(df, size_df, col):
    perm_df = df.reindex(np.random.permutation(df.index))
    res_df = pd.DataFrame({}, columns = df.columns)
    unique_parts = perm_df[col].unique()
    num_parts = int(size_df / len(unique_parts)) 
    for unique in unique_parts:
        selected_rows = perm_df[perm_df[col] == unique]
        res_df = pd.concat([res_df, selected_rows[:num_parts]])
    
    return res_df.reindex(np.random.permutation(res_df.index))

In [26]:
if not onlyMpqa:
    test_reviews_even = equal_cuts(expectedResultsImdb, 2500, 'rating')
    sentencesTestSubsetImdb = sentencesImdb[sentencesImdb['real-id'].isin(test_reviews_even['real-id'])]

    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row: processWordsMovies(row), axis = 1)
    tEnd = time.time()
    print("Timed Process Movies data: {}".format(str(tEnd - tStart)))
    
    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row: remove_articles(row), axis = 1) 
    tEnd = time.time()
    print("Timed Remove Articles IMDB: {}".format(str(tEnd-tStart)))
    test_reviews_even['expected'] = test_reviews_even['type']

Timed Process Movies data: 56.2809998989
Timed Remove Articles IMDB: 15.385999918


In [27]:
def countNegations(row):
    words = row['textArrStemmed']
    negations['found'] = negations.apply(lambda row: 1 if row['phraseStemmed'] in words else 0, axis = 1)
    row['negations'] = negations['found'].sum()
    return row

In [28]:
tStart = time.time()
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row: countNegations(row), axis = 1)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

Timed MPQA: 5.78299999237


In [29]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row: countNegations(row), axis = 1)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed IMDB: 35.0899999142


In [30]:
polarizedSentencesMpqa['negations'].value_counts()

0    4089
1     522
2       1
Name: negations, dtype: int64

In [31]:
if not onlyMpqa:
    sentencesTestSubsetImdb['negations'].value_counts()

In [32]:
featureColumnsMpqa = {'punctuation' : 1, 'negations' : 1}
featureColumnsImdb = {'punctuation' : 1, 'negations' : 1}

In [33]:
def binSearchDfValue(df, val, start, end, isDebug = False):
    while start <= end:
        if isDebug:
            print("Start: {};    End: {}".format(start, end))
        middle = (start + end) / 2
        if isDebug:
            print("middle: {}".format(df[middle]))
        if df[middle] == val:
            return True
        else:
            if df[middle] > val:
                end = middle - 1
            else:
                start = middle + 1
    
    return False

def countOccurenceInColumn(row, lookFor, lookForLen, columnName):
    words = row['textArr']
    res = [word for word in words if binSearchDfValue(lookFor, word, 0, lookForLen)]
    row[columnName] = len(res)
    return row

def CalculateColumnCounts(colArr, column, df, val = None, typeWord = None):
    compareVal = column
    if column == None:
        columnName = "All"+typeWord
    else:
        if val != None:
            compareVal = val
        columnName = column+'Count'
        if val != None:
            columnName = columnName + val
        if typeWord != None:
            columnName = columnName + typeWord
        
    if typeWord == None:
        lookFor = sentimentDictionary[sentimentDictionary[column] == compareVal]
    else:
        if column == None:
            lookFor = sentimentDictionary[(sentimentDictionary['type'] == typeWord)]
        else:
            lookFor = sentimentDictionary[(sentimentDictionary[column] == compareVal) & (sentimentDictionary['type'] == typeWord)]
    
    lookForVals = lookFor['entry'].values
    lookForLen = len(lookForVals) - 1
    print("LookFor shape: {}".format(lookFor.shape))
    df[columnName]  = 0
    tStart = time.time()
    df = df.apply(lambda row: countOccurenceInColumn(row, lookForVals, lookForLen, columnName), axis = 1)
    tEnd = time.time()
    print("Timed({}): {}".format(columnName, str(tEnd-tStart)))
    colArr[columnName] = 1
    
    return df, colArr

In [34]:
def calculateReiredColumnCounts(df, colArr):
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'negative')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'both')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'neutral')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'positive')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'negative', 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'positive', 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'neutral', 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'both', 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'negative', 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'positive', 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'both', 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'priorpolarity', df, 'neutral', 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, None, df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, None, df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'hostile', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'strong', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'hostile', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'strong', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'hostile', df)
    df, colArr = CalculateColumnCounts(colArr, 'strong', df)
    df, colArr = CalculateColumnCounts(colArr, 'active', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'passive', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'active', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'passive', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'active', df)
    df, colArr = CalculateColumnCounts(colArr, 'passive', df)
    df, colArr = CalculateColumnCounts(colArr, 'positiv', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'negativ', df, None, 'weaksubj')
    df, colArr = CalculateColumnCounts(colArr, 'positiv', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'negativ', df, None, 'strongsubj')
    df, colArr = CalculateColumnCounts(colArr, 'positiv', df)
    df, colArr = CalculateColumnCounts(colArr, 'negativ', df)
    df, colArr = CalculateColumnCounts(colArr, 'yes', df)
    df, colArr = CalculateColumnCounts(colArr, 'no', df)

    return df, colArr

In [35]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb, featureColumnsImdb = calculateReiredColumnCounts(sentencesTestSubsetImdb, featureColumnsImdb)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

LookFor shape: (1552, 26)
Timed(priorpolarityCountnegative): 11.8569998741
LookFor shape: (7, 26)
Timed(priorpolarityCountboth): 10.8300001621
LookFor shape: (137, 26)
Timed(priorpolarityCountneutral): 8.60699987411
LookFor shape: (1040, 26)
Timed(priorpolarityCountpositive): 9.75
LookFor shape: (972, 26)
Timed(priorpolarityCountnegativestrongsubj): 11.4480001926
LookFor shape: (584, 26)
Timed(priorpolarityCountpositivestrongsubj): 8.84800004959
LookFor shape: (45, 26)
Timed(priorpolarityCountneutralstrongsubj): 6.31900000572
LookFor shape: (6, 26)
Timed(priorpolarityCountbothstrongsubj): 5.5640001297
LookFor shape: (580, 26)
Timed(priorpolarityCountnegativeweaksubj): 8.63199996948
LookFor shape: (456, 26)
Timed(priorpolarityCountpositiveweaksubj): 9.60299992561
LookFor shape: (1, 26)
Timed(priorpolarityCountbothweaksubj): 6.95199990273
LookFor shape: (92, 26)
Timed(priorpolarityCountneutralweaksubj): 8.49699997902
LookFor shape: (1129, 26)
Timed(Allweaksubj): 9.99300003052
LookFor sha

In [36]:
tStart = time.time()
polarizedSentencesMpqa, featureColumnsMpqa = calculateReiredColumnCounts(polarizedSentencesMpqa, featureColumnsMpqa)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

LookFor shape: (1552, 26)
Timed(priorpolarityCountnegative): 1.15100002289
LookFor shape: (7, 26)
Timed(priorpolarityCountboth): 0.708999872208
LookFor shape: (137, 26)
Timed(priorpolarityCountneutral): 0.956000089645
LookFor shape: (1040, 26)
Timed(priorpolarityCountpositive): 1.13899993896
LookFor shape: (972, 26)
Timed(priorpolarityCountnegativestrongsubj): 1.04000020027
LookFor shape: (584, 26)
Timed(priorpolarityCountpositivestrongsubj): 1.09200000763
LookFor shape: (45, 26)
Timed(priorpolarityCountneutralstrongsubj): 0.84500002861
LookFor shape: (6, 26)
Timed(priorpolarityCountbothstrongsubj): 0.826999902725
LookFor shape: (580, 26)
Timed(priorpolarityCountnegativeweaksubj): 0.99799990654
LookFor shape: (456, 26)
Timed(priorpolarityCountpositiveweaksubj): 1.10099983215
LookFor shape: (1, 26)
Timed(priorpolarityCountbothweaksubj): 0.655000209808
LookFor shape: (92, 26)
Timed(priorpolarityCountneutralweaksubj): 0.980999946594
LookFor shape: (1129, 26)
Timed(Allweaksubj): 1.03800010

In [37]:
featureColumnsMpqa.keys()

['negativCountweaksubj',
 'priorpolarityCountpositive',
 'negativCount',
 'activeCount',
 'Allstrongsubj',
 'positivCountstrongsubj',
 'activeCountweaksubj',
 'positivCount',
 'passiveCount',
 'noCount',
 'negativCountstrongsubj',
 'punctuation',
 'priorpolarityCountneutralstrongsubj',
 'priorpolarityCountnegativeweaksubj',
 'priorpolarityCountneutral',
 'priorpolarityCountpositivestrongsubj',
 'hostileCountstrongsubj',
 'strongCountweaksubj',
 'priorpolarityCountbothweaksubj',
 'priorpolarityCountbothstrongsubj',
 'priorpolarityCountnegative',
 'positivCountweaksubj',
 'passiveCountweaksubj',
 'priorpolarityCountneutralweaksubj',
 'priorpolarityCountboth',
 'Allweaksubj',
 'negations',
 'priorpolarityCountpositiveweaksubj',
 'priorpolarityCountnegativestrongsubj',
 'strongCountstrongsubj',
 'strongCount',
 'passiveCountstrongsubj',
 'yesCount',
 'hostileCount',
 'hostileCountweaksubj',
 'activeCountstrongsubj']

In [38]:
def countOccurenceColumnBeforeAfter(row, lookFor, columnName):
    global negations
    for _, neg_row in negations.iterrows():
        neg = '|'+neg_row['phrase']+'|'
        neg_stemmed = '|' + neg_row['phraseStemmed'] + '|'
        posNeg = row['text'].find(neg)
        if posNeg == -1 :
            return row
        posNeg = row['textStemmed'].find(neg_stemmed)

        afterPos = posNeg + len(neg_stemmed)
        for _, rowLook in lookFor.iterrows():
            posBefore = row['textStemmed'].find(rowLook['entry'], 0, posNeg)
            posAfter = row['textStemmed'].find(rowLook['entry'], afterPos)

            if posBefore != -1:
                row[columnName+'Before'] = row[columnName+'Before'] + 1 
            if posAfter != -1:
                row[columnName+'After'] = row[columnName+'After'] + 1

    return row


def WordsAroundNegations(colArr, column, df, val = None, count = False):
    columnName = column
    compareVal = val
    if val is None:
        compareVal = column
    else:
        columnName = column + val
    
    if count:
        columnName = columnName + "Count"
    
    lookFor = sentimentDictionary[sentimentDictionary[column] == compareVal]
    
    print("LookFor shape: {}".format(lookFor.shape))
    if count:
        df[columnName+"Before"]  = 0
        df[columnName+"After"]  = 0
    else:
        df[columnName+"Before"]  = False
        df[columnName+"After"]  = False
        foundCount = columnName + "CountBefore" in df.columns

    tStart = time.time()
    if count:
        df = df.apply(lambda row: countOccurenceColumnBeforeAfter(row, lookFor, columnName), axis = 1)
    else:
        df[columnName+'Before'] = df[columnName + "CountBefore"] > 0
        df[columnName+'After'] = df[columnName + "CountAfter"] > 0
        
    tEnd = time.time()
    print("Timed({}): {}".format(columnName, str(tEnd-tStart)))

    colArr[columnName+"Before"] = 1
    colArr[columnName+"After"] = 1
    
    return df, colArr

In [39]:
def calculateRequiredWordsAroundNegations(df, colArr):   
    df, colArr = WordsAroundNegations(colArr, 'active', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'passive', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'hostile', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'yes', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'no', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'negate', df, None, True)
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'negative', True)
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'positive', True)
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'both', True)
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'neutral', True)
    
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'negative')
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'positive')
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'neutral')
    df, colArr = WordsAroundNegations(colArr, 'priorpolarity', df, 'both')
    df, colArr = WordsAroundNegations(colArr, 'active', df)
    df, colArr = WordsAroundNegations(colArr, 'passive', df)
    df, colArr = WordsAroundNegations(colArr, 'hostile', df)
    df, colArr = WordsAroundNegations(colArr, 'yes', df)
    df, colArr = WordsAroundNegations(colArr, 'no', df)
    df, colArr = WordsAroundNegations(colArr, 'negate', df)
    return df, colArr

In [40]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb, featureColumnsImdb = calculateRequiredWordsAroundNegations(sentencesTestSubsetImdb, featureColumnsImdb)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

LookFor shape: (610, 26)
Timed(activeCount): 153.782999992
LookFor shape: (369, 26)
Timed(passiveCount): 95.493999958
LookFor shape: (478, 26)
Timed(hostileCount): 120.585999966
LookFor shape: (8, 26)
Timed(yesCount): 9.61699986458
LookFor shape: (4, 26)
Timed(noCount): 8.60299992561
LookFor shape: (128, 26)
Timed(negateCount): 37.8949999809
LookFor shape: (1552, 26)
Timed(priorpolaritynegativeCount): 374.960999966
LookFor shape: (1040, 26)
Timed(priorpolaritypositiveCount): 287.818999767
LookFor shape: (7, 26)
Timed(priorpolaritybothCount): 11.368999958
LookFor shape: (137, 26)
Timed(priorpolarityneutralCount): 46.7899999619
LookFor shape: (1552, 26)
Timed(priorpolaritynegative): 0.0
LookFor shape: (1040, 26)
Timed(priorpolaritypositive): 0.0
LookFor shape: (137, 26)
Timed(priorpolarityneutral): 0.00100016593933
LookFor shape: (7, 26)
Timed(priorpolarityboth): 0.000999927520752
LookFor shape: (610, 26)
Timed(active): 0.000999927520752
LookFor shape: (369, 26)
Timed(passive): 0.0010001

In [41]:
tStart = time.time()
polarizedSentencesMpqa, featureColumnsMpqa = calculateRequiredWordsAroundNegations(polarizedSentencesMpqa, featureColumnsMpqa)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

LookFor shape: (610, 26)
Timed(activeCount): 30.7259998322
LookFor shape: (369, 26)
Timed(passiveCount): 19.7960000038
LookFor shape: (478, 26)
Timed(hostileCount): 22.6879999638
LookFor shape: (8, 26)
Timed(yesCount): 2.53299999237
LookFor shape: (4, 26)
Timed(noCount): 1.48399996758
LookFor shape: (128, 26)
Timed(negateCount): 7.05500006676
LookFor shape: (1552, 26)
Timed(priorpolaritynegativeCount): 72.992000103
LookFor shape: (1040, 26)
Timed(priorpolaritypositiveCount): 51.3429999352
LookFor shape: (7, 26)
Timed(priorpolaritybothCount): 1.69900012016
LookFor shape: (137, 26)
Timed(priorpolarityneutralCount): 7.40300011635
LookFor shape: (1552, 26)
Timed(priorpolaritynegative): 0.000999927520752
LookFor shape: (1040, 26)
Timed(priorpolaritypositive): 0.00100016593933
LookFor shape: (137, 26)
Timed(priorpolarityneutral): 0.00100016593933
LookFor shape: (7, 26)
Timed(priorpolarityboth): 0.0
LookFor shape: (610, 26)
Timed(active): 0.000999927520752
LookFor shape: (369, 26)
Timed(passi

In [42]:
featureColumnsMpqa

{'Allstrongsubj': 1,
 'Allweaksubj': 1,
 'activeAfter': 1,
 'activeBefore': 1,
 'activeCount': 1,
 'activeCountAfter': 1,
 'activeCountBefore': 1,
 'activeCountstrongsubj': 1,
 'activeCountweaksubj': 1,
 'hostileAfter': 1,
 'hostileBefore': 1,
 'hostileCount': 1,
 'hostileCountAfter': 1,
 'hostileCountBefore': 1,
 'hostileCountstrongsubj': 1,
 'hostileCountweaksubj': 1,
 'negateAfter': 1,
 'negateBefore': 1,
 'negateCountAfter': 1,
 'negateCountBefore': 1,
 'negations': 1,
 'negativCount': 1,
 'negativCountstrongsubj': 1,
 'negativCountweaksubj': 1,
 'noAfter': 1,
 'noBefore': 1,
 'noCount': 1,
 'noCountAfter': 1,
 'noCountBefore': 1,
 'passiveAfter': 1,
 'passiveBefore': 1,
 'passiveCount': 1,
 'passiveCountAfter': 1,
 'passiveCountBefore': 1,
 'passiveCountstrongsubj': 1,
 'passiveCountweaksubj': 1,
 'positivCount': 1,
 'positivCountstrongsubj': 1,
 'positivCountweaksubj': 1,
 'priorpolarityCountboth': 1,
 'priorpolarityCountbothstrongsubj': 1,
 'priorpolarityCountbothweaksubj': 1,
 

In [43]:
sentimentDictionary['stemmed'].shape[0]

2736L

In [44]:
def create_n_grams(row, size_ngram):
    row[str(size_ngram)+"_gram"] = list(ngrams(row['tokens'], size_ngram))
    return row

def countOneBeforeOtherNgranRow(row, col, size_ngram, beforeSeries, afterSeries):
    # first, try to find a word from "after series"
    n_gram_col = str(size_ngram)+'_gram' 
    for n_gram in row[n_gram_col]:
        for idx in range(1, size_ngram):
            w = n_gram[idx]
            found = binSearchDfValue(afterSeries, w, 0, afterSeries.shape[0] - 1)
            if found:
                for idx_sub in range(0, idx):
                    w2 = n_gram[idx_sub]
                    found_sub = binSearchDfValue(beforeSeries, w2, 0, beforeSeries.shape[0] - 1)
                    if found_sub:
                        row[col] = row[col] + 1
    return row
    
def countOneBeforeOtherNgramDf(colArr, df, size_ngram, beforeClassCol, afterClassCol, beforeClassVal = None, afterClassVal = None, beforeSerieDefault = None):
    columnName = 'ngram_'+str(size_ngram)+"_"+ beforeClassCol + afterClassCol
    compareValBefore = beforeClassVal
    if beforeClassVal is None:
        compareValBefore = beforeClassCol
    else:
        columnName = columnName + beforeClassVal
    
    if beforeSerieDefault is None:
        lookForBefore = sentimentDictionary[sentimentDictionary[beforeClassCol] == compareValBefore].reset_index(drop=True)
        lookForBefore = lookForBefore['entry']
    else:
        lookForBefore = beforeSerieDefault

    compareValAfter = afterClassVal
    if afterClassVal is None:
        compareValAfter = afterClassCol
    else:
        columnName = columnName + afterClassVal
    
    lookForAfter = sentimentDictionary[sentimentDictionary[afterClassCol] == compareValAfter].reset_index(drop=True)
    lookForAfter = lookForAfter['entry']
    
    df[columnName]  = 0
    tStart = time.time()
    df = df.apply(lambda row: countOneBeforeOtherNgranRow(row, columnName, size_ngram, lookForBefore, lookForAfter), axis = 1)
    tEnd = time.time()
    print("Timed({}): {}".format(columnName, str(tEnd-tStart)))
    
    colArr[columnName] = 1
    return df, colArr

In [45]:
tStart = time.time()
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row:create_n_grams(row, 2), axis = 1)
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row:create_n_grams(row, 3), axis = 1)
polarizedSentencesMpqa = polarizedSentencesMpqa.apply(lambda row:create_n_grams(row, 4), axis = 1)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

Timed MPQA: 8.90600013733


In [46]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams(row, 2), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams(row, 3), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams(row, 4), axis = 1)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed IMDB: 52.9670000076


In [47]:
def calculateBeforeAfterNgrams(df, colArr):
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negativ', 'priorpolarity', None, 'positive')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negativ', 'priorpolarity', None, 'positive')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negativ', 'priorpolarity', None, 'positive')
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negativ', 'priorpolarity', None, 'negative')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negativ', 'priorpolarity', None, 'negative')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negativ', 'priorpolarity', None, 'negative')

    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negativ', 'priorpolarity', None, 'neutral')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negativ', 'priorpolarity', None, 'neutral')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negativ', 'priorpolarity', None, 'neutral')

    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negations', 'priorpolarity', None, 'positive', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negations', 'priorpolarity', None, 'positive', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negations', 'priorpolarity', None, 'positive', negations['phraseStemmed'])
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negations', 'priorpolarity', None, 'negative', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negations', 'priorpolarity', None, 'negative', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negations', 'priorpolarity', None, 'negative', negations['phraseStemmed'])
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'negations', 'priorpolarity', None, 'neutral', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'negations', 'priorpolarity', None, 'neutral', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'negations', 'priorpolarity', None, 'neutral', negations['phraseStemmed'])
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'hostile', 'priorpolarity', None, 'negative')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'hostile', 'priorpolarity', None, 'negative')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 4, 'hostile', 'priorpolarity', None, 'negative')

    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'persist', 'priorpolarity', None, 'positive')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'persist', 'priorpolarity', None, 'positive')
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'pleasur', 'priorpolarity', None, 'positive')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'pleasur', 'priorpolarity', None, 'positive')
    
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'weak', 'priorpolarity', None, 'negative')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'weak', 'priorpolarity', None, 'negative')

    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 2, 'active', 'priorpolarity', None, 'positive')
    df, colArr = countOneBeforeOtherNgramDf(colArr, df, 3, 'active', 'priorpolarity', None, 'positive')
    return df, colArr

In [48]:
sentimentDictionary.columns

Index([u'positiv', u'negativ', u'active', u'passive', u'affil', u'hostile',
       u'strong', u'power', u'weak', u'submit', u'yes', u'no', u'negate',
       u'intrj', u'pleasur', u'pain', u'feel', u'need', u'persist', u'entry',
       u'othtags', u'type', u'pos', u'stemmed', u'priorpolarity', u'entryRaw'],
      dtype='object')

In [49]:
tStart = time.time()
polarizedSentencesMpqa, featureColumnsMpqa = calculateBeforeAfterNgrams(polarizedSentencesMpqa, featureColumnsMpqa)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

Timed(ngram_2_negativpriorpolaritypositive): 8.53000020981
Timed(ngram_3_negativpriorpolaritypositive): 15.5979998112
Timed(ngram_4_negativpriorpolaritypositive): 25.0409998894
Timed(ngram_2_negativpriorpolaritynegative): 12.0720000267
Timed(ngram_3_negativpriorpolaritynegative): 15.9429998398
Timed(ngram_4_negativpriorpolaritynegative): 25.1419999599
Timed(ngram_2_negativpriorpolarityneutral): 6.16499996185
Timed(ngram_3_negativpriorpolarityneutral): 10.9130001068
Timed(ngram_4_negativpriorpolarityneutral): 16.3870000839
Timed(ngram_2_negationspriorpolaritypositive): 8.71199989319
Timed(ngram_3_negationspriorpolaritypositive): 15.0309998989
Timed(ngram_4_negationspriorpolaritypositive): 22.5639998913
Timed(ngram_2_negationspriorpolaritynegative): 11.0149998665
Timed(ngram_3_negationspriorpolaritynegative): 18.6579999924
Timed(ngram_4_negationspriorpolaritynegative): 23.6690001488
Timed(ngram_2_negationspriorpolarityneutral): 7.02800011635
Timed(ngram_3_negationspriorpolarityneutral): 

In [50]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb, featureColumnsImdb = calculateBeforeAfterNgrams(sentencesTestSubsetImdb, featureColumnsImdb)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed(ngram_2_negativpriorpolaritypositive): 70.5460000038
Timed(ngram_3_negativpriorpolaritypositive): 132.561000109
Timed(ngram_4_negativpriorpolaritypositive): 193.453999996
Timed(ngram_2_negativpriorpolaritynegative): 73.2899999619
Timed(ngram_3_negativpriorpolaritynegative): 149.536000013
Timed(ngram_4_negativpriorpolaritynegative): 190.314999819
Timed(ngram_2_negativpriorpolarityneutral): 49.1549999714
Timed(ngram_3_negativpriorpolarityneutral): 89.3830001354
Timed(ngram_4_negativpriorpolarityneutral): 127.005999804
Timed(ngram_2_negationspriorpolaritypositive): 64.9549999237
Timed(ngram_3_negationspriorpolaritypositive): 120.125
Timed(ngram_4_negationspriorpolaritypositive): 170.684000015
Timed(ngram_2_negationspriorpolaritynegative): 68.4849998951
Timed(ngram_3_negationspriorpolaritynegative): 125.148000002
Timed(ngram_4_negationspriorpolaritynegative): 178.411999941
Timed(ngram_2_negationspriorpolarityneutral): 48.2509999275
Timed(ngram_3_negationspriorpolarityneutral): 86.483

In [51]:
polarizedSentencesMpqa

index         docName   dirName  idx  startByte  endByte  sentLen  \
0         0  13.40.05-15087  20010620    0        109      226      117   
1         7  13.40.05-15087  20010620    7        793      884       91   
2        11  13.40.05-15087  20010620   11        656      749       93   
3        13  13.40.05-15087  20010620   13        588      655       67   
5        26  23.46.20-17835  20010627   11       1466     1597      131   
7        31  00.48.42-17806  20010630    3       2648     2698       50   
9        34  00.48.42-17806  20010630    6       4017     4133      116   
11       37  00.48.42-17806  20010630    9       2507     2641      134   
12       38  00.48.42-17806  20010630   10       3931     4016       85   
22       50  00.48.42-17806  20010630   22       2421     2506       85   
23       51  00.48.42-17806  20010630   23       2699     2792       93   
24       52  00.48.42-17806  20010630   24       3144     3278      134   
26       56   01.24.22-5235  20010705    2        258      400      142   
27       61   01.24.22-5235  20010705    7        546      621       75   
28       68  02.01.27-21386  20010706    3        659      727       68   
42       88   00.31.31-4544  20010715    3       2259     2354       95   
46       93   00.31.31-4544  20010715    8       1964     2128      164   
47       95   00.31.31-4544  20010715   10       2135     2205       70   
49       97   00.31.31-4544  20010715   12       2206     2252       46   
51       99   01.37.46-4752  20010717    0          2       78       76   
57      107  00.42.54-29681  20010718    3        873     1024      151   
58      109  00.42.54-29681  20010718    5        764      872      108   
61      130   23.12.58-1993  20010813    5        640      770      130   
68      140  01.09.50-14694  20010818    3          2       51       49   
69      141  01.09.50-14694  20010818    4       1488     1547       59   
72      144  01.09.50-14694  20010818    7       3267     3372      105   
74      146  01.09.50-14694  20010818    9       1639     1781      142   
77      150  01.09.50-14694  20010818   13       3373     3449       76   
78      152  01.09.50-14694  20010818   15       1082     1210      128   
79      153  01.09.50-14694  20010818   16         80      232      152   
...     ...             ...       ...  ...        ...      ...      ...   
9499  15468        wsj_0768     xbank   22       1839     1929       90   
9500  15473        wsj_0768     xbank   27       1932     2042      110   
9501  15482        wsj_0768     xbank   36       3700     3790       90   
9502  15483        wsj_0768     xbank   37       4077     4160       83   
9512  15514        wsj_0778     xbank   20       3662     3767      105   
9516  15527        wsj_0805     xbank    3         26      158      132   
9517  15554        wsj_0815     xbank    2        138      288      150   
9518  15560        wsj_0816     xbank    1        462      601      139   
9519  15561        wsj_0816     xbank    2          9      157      148   
9520  15562        wsj_0816     xbank    3        938     1091      153   
9521  15570        wsj_0816     xbank   11       1092     1156       64   
9527  15609        wsj_0923     xbank    1        148      232       84   
9528  15612        wsj_0923     xbank    4        235      342      107   
9529  15613        wsj_0923     xbank    5         31      145      114   
9530  15619        wsj_0924     xbank    5         31       95       64   
9531  15628        wsj_0927     xbank    4        795      894       99   
9532  15629        wsj_0927     xbank    5        972     1013       41   
9533  15635        wsj_0927     xbank   11       1014     1111       97   
9534  15637        wsj_0927     xbank   13       1928     1993       65   
9535  15645        wsj_0927     xbank   21       1503     1584       81   
9537  15648        wsj_0927     xbank   24        896      970       74   
9539  15670        wsj_0928    

In [52]:
import cPickle as pickle
if doSave:
#    with open('./clean-sentiment-mpqa.dump','wb') as fp:
#        pickle.dump(polarizedSentencesMpqa,fp)
#    with open('./clean-sentiment-imdb-sents.dump','wb') as fp:
#        pickle.dump(sentencesTestSubsetImdb,fp)
    with open('./clean-sentiment-sentences.dump','wb') as fp:
        pickle.dump(selectedPolarizedSentencesMpqa,fp)    

In [53]:
sentiment_positive = 1
sentiment_negative = -1
polarizedSentencesMpqa.loc[polarizedSentencesMpqa['sentiment-intensity'] < 0, 'sentiment-intensity'] = sentiment_negative
polarizedSentencesMpqa.loc[polarizedSentencesMpqa['sentiment-intensity'] > 0, 'sentiment-intensity'] = sentiment_positive

In [54]:
def get_equal_sentiment_parts(df, ratio):
    neg_df = df[df['sentiment-intensity'] < 0].shape[0]
    pos_df = df[df['sentiment-intensity'] > 0].shape[0]
    neutral_df = df[df['sentiment-intensity'] == 0].shape[0]
    min_size = min(neg_df, pos_df, neutral_df)
    
    new_df = pd.concat([df[df['sentiment-intensity'] < 0][:min_size],df[df['sentiment-intensity'] > 0][:int(ratio * min_size)], df[df['sentiment-intensity'] == 0][:min_size]])
    return new_df.reindex(np.random.permutation(new_df.index))

def get_equal_neutral_training_sentiment_parts(df, ratio):
    new_df = df.reindex(np.random.permutation(df.index))
    
    neg_df = df[df['sentiment-intensity'] < 0].shape[0]
    pos_df = df[df['sentiment-intensity'] > 0].shape[0]
    neutral_df = df[df['sentiment-intensity'] == 0].shape[0]
    min_size = min(neg_df, pos_df, neutral_df)
    if min_size * 2 > neutral_df:
        min_size = int(neutral_df / 2)
    
    new_df = pd.concat([new_df[new_df['sentiment-intensity'] < 0][:int(min_size *  ratio)],new_df[new_df['sentiment-intensity'] > 0][:int(ratio * min_size)],
                            new_df[new_df['sentiment-intensity'] == 0][:int(min_size * ratio)]])
    
    new_df['sentiment-neutral'] = 0
    new_df.loc[new_df['sentiment-intensity'] == 0, 'sentiment-neutral'] = 1
    return new_df.reindex(np.random.permutation(new_df.index))

In [55]:
if not onlyMpqa:
    test_reviews_even.loc[test_reviews_even['expected'] < 0, 'expected'] = sentiment_negative
    test_reviews_even.loc[test_reviews_even['expected'] > 0, 'expected'] = sentiment_positive

In [56]:
def show_all_value_counts(df):
    skip = ['index', 'docName', 'dirName', 'idx', 'startByte', 'endByte', 'sentLen', 'annotsCount', 'text', 'sentiment-measured',
       'sentiment-type', 'sentiment-intensity', 'textLower', 'textList', 'wordCount', 'textArr', 'textStemmed', 'textArrStemmed',
        'id', 'rating', 'set', 'type', 'real-id']
    
    for col in df.columns:
        if col in skip:
            continue
         
        print
        print("Column: {}".format(col))
        print(df[col].value_counts())

In [57]:
# show_all_value_counts(sentencesTestSubsetImdb)

In [58]:
# show_all_value_counts(selectedPolarizedSentencesMpqa)

In [59]:
def calculateRequiredMoreThanOther(df, colArr):
    df['morePositiveThanNegativeStrong'] = False
    dt = df[df['priorpolarityCountpositivestrongsubj'] > df['priorpolarityCountnegativestrongsubj'] ]
    df.loc[dt.index,'morePositiveThanNegativeStrong'] = True
    colArr['morePositiveThanNegativeStrong'] = 1

    df['morePositiveThanNegativeWeak'] = False
    dt = df[df['priorpolarityCountpositiveweaksubj'] > df['priorpolarityCountnegativeweaksubj'] ]
    df.loc[dt.index,'morePositiveThanNegativeWeak'] = True
    colArr['morePositiveThanNegativeWeak'] = 1

    df['morePositiveThanNegative'] = False
    dt = df[df['priorpolarityCountpositive'] > df['priorpolarityCountnegative'] ]
    df.loc[dt.index,'morePositiveThanNegative'] = True
    colArr['morePositiveThanNegative'] = 1

    df['morePositiveThanNeutral'] = False
    dt = df[df['priorpolarityCountpositive'] > df['priorpolarityCountneutral'] ]
    df.loc[dt.index,'morePositiveThanNeutral'] = True
    colArr['morePositiveThanNeutral'] = 1

    df['moreNegativeThanNeutral'] = False
    dt = df[df['priorpolarityCountnegative'] > df['priorpolarityCountneutral'] ]
    df.loc[dt.index,'moreNegativeThanNeutral'] = True
    colArr['moreNegativeThanNeutral'] = 1
    return df, colArr

In [60]:
polarizedSentencesMpqa, featureColumnsMpqa = calculateRequiredMoreThanOther(polarizedSentencesMpqa, featureColumnsMpqa)
if not onlyMpqa:
    sentencesTestSubsetImdb, featureColumnsImdb = calculateRequiredMoreThanOther(sentencesTestSubsetImdb, featureColumnsImdb)
print

In [61]:
selectedPolarizedSentencesMpqa = get_equal_sentiment_parts(polarizedSentencesMpqa[polarizedSentencesMpqa['annotsCount'] > 1], 1.0)
#with open('./clean-sentiment-sentences.dump','rb') as fp:
#    selectedPolarizedSentencesMpqa = pickle.load(fp)    
selectedPolarizedSentencesMpqa.shape

(1932, 132)

In [62]:
#neutralSelectedSentencesMpqa = get_equal_neutral_training_sentiment_parts(polarizedSentencesMpqa, 1)
#neutralSelectedSentencesMpqa.shape

In [63]:
from textblob import TextBlob
from textblob_aptagger import PerceptronTagger

pos_tagger = PerceptronTagger()

def assign_pos_tags(row):
    tagged_words = TextBlob(row['textRaw'], pos_tagger= pos_tagger)
    row['textPos'] = tagged_words.tags
    return row

In [64]:
tStart = time.time()
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row: assign_pos_tags(row), axis = 1)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row: assign_pos_tags(row), axis = 1)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed MPQA: 4.06200003624
Timed IMDB: 41.8919999599


In [65]:
tags = [gram[1] for gram_list in selectedPolarizedSentencesMpqa['textPos'].values for gram in gram_list]
tags_pd = pd.DataFrame(tags, columns=["tag"])
tags_pd['tag'].value_counts()

NN      4508
IN      3697
DT      3593
NNP     2788
JJ      2268
NNS     1821
RB      1518
VB      1310
VBD     1197
PRP     1093
VBZ     1082
TO       930
VBN      861
CC       822
VBP      623
VBG      599
MD       571
PRP$     361
CD       312
POS      264
NNPS     168
WDT      143
WP       117
EX        95
JJR       86
WRB       81
RP        80
RBR       46
JJS       42
PDT       28
RBS       15
WP$        6
FW         5
UH         4
SYM        1
Name: tag, dtype: int64

In [66]:
def create_n_grams_pos(row, size_ngram):
    row["pos_"+str(size_ngram)+"_gram"] = list(ngrams(row['textPos'], size_ngram))
    return row

def countOneBeforeOtherNgranPosRow(row, col, size_ngram, beforeSeries, afterSeries, beforeSeriesPos = None, afterSeriesPos = None):
    # first, try to find a word from "after series"
    n_gram_col = 'pos_'+str(size_ngram)+'_gram' 
    for n_gram in row[n_gram_col]:
        for idx in range(1, size_ngram):
            w = n_gram[idx]
            if afterSeriesPos is not None and w[1] not in afterSeriesPos:
                continue

            found = binSearchDfValue(afterSeries, w[0], 0, afterSeries.shape[0] - 1)
            if found:
                for idx_sub in range(0, idx):
                    w2 = n_gram[idx_sub]
                    if beforeSeriesPos is not None and w2[1] not in beforeSeriesPos:
                        continue
                    found_sub = binSearchDfValue(beforeSeries, w2[0], 0, beforeSeries.shape[0] - 1)
                    if found_sub:
                        row[col] = row[col] + 1
    return row
    
def countOneBeforeOtherNgramPosDf(colArr, df, size_ngram, beforeClassCol, afterClassCol,
                                  beforeClassPos = None, afterClassPos = None,
                                beforeClassVal = None, afterClassVal = None, beforeSerieDefault = None):
    columnName = 'pos_ngram_'+str(size_ngram)+"_" + '.'.join(beforeClassPos) + '.'.join(afterClassPos)
    if beforeClassCol is not None:
        columnName += beforeClassCol
    if afterClassCol is not None:
        columnName += afterClassCol
    
    
    compareValBefore = beforeClassVal
    if beforeClassVal is None:
        compareValBefore = beforeClassCol
    else:
        columnName = columnName + beforeClassVal
    
    if beforeSerieDefault is None:
        if beforeClassCol is None:
                lookForBefore = sentimentDictionary.reset_index(drop = True)
                lookForBefore = lookForBefore['entryRaw']
        else:
            lookForBefore = sentimentDictionary[sentimentDictionary[beforeClassCol] == compareValBefore].reset_index(drop=True)
            lookForBefore = lookForBefore['entryRaw']
    else:
        lookForBefore = beforeSerieDefault

    compareValAfter = afterClassVal
    if afterClassVal is None:
        compareValAfter = afterClassCol
    else:
        columnName = columnName + afterClassVal
    
    if afterClassCol is None:
        lookForAfter = sentimentDictionary.reset_index(drop = True)
        lookForAfter = lookForAfter['entryRaw']
    else:
        lookForAfter = sentimentDictionary[sentimentDictionary[afterClassCol] == compareValAfter].reset_index(drop=True)
        lookForAfter = lookForAfter['entryRaw']
    
    df[columnName]  = 0
    tStart = time.time()
    df = df.apply(lambda row: countOneBeforeOtherNgranPosRow(row, columnName, size_ngram, lookForBefore, lookForAfter, beforeClassPos, afterClassPos), axis = 1)
    tEnd = time.time()
    print("Timed({}): {}".format(columnName, str(tEnd-tStart)))
    
    colArr[columnName] = 1
    return df, colArr

In [67]:
sentencesTestSubsetImdb['textRaw'] = sentencesTestSubsetImdb['text'].map(lambda cell: ' '.join(cell.split('|')))

In [68]:
tStart = time.time()
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row:create_n_grams_pos(row, 4), axis = 1)
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row:create_n_grams_pos(row, 5), axis = 1)
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row:create_n_grams_pos(row, 6), axis = 1)
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row:create_n_grams_pos(row, 7), axis = 1)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams_pos(row, 2), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams_pos(row, 4), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams_pos(row, 5), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams_pos(row, 6), axis = 1)
    sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row:create_n_grams_pos(row, 7), axis = 1)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

Timed MPQA: 4.96099996567
Timed IMDB: 78.6540000439


In [69]:
def calculateBeforeAfterNgramsPos(df, colArr):
    verb_tags = ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']
    noun_tags = ['NN', 'NNP', 'NNS']
    adjective_tags = ['JJ', 'JJR', 'JJS']
    adjective_adverb_tags = adjective_tags + ['RB', 'RBR', 'RBS']
    print(adjective_adverb_tags)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'positiv', adjective_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'positiv', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'positiv', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'positiv', adjective_tags, noun_tags, None, None)

    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'active', adjective_adverb_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'active', adjective_adverb_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'active', adjective_adverb_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'active', adjective_adverb_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'strong', adjective_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'strong', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'strong', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'strong', adjective_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'negativ', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'negativ', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'negativ', adjective_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, 'negations', 'priorpolarity', 'ADJ', 'NOUN', None, 'positive', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, 'negations', 'priorpolarity', 'ADJ', 'NOUN', None, 'positive', negations['phraseStemmed'])
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, 'negations', 'priorpolarity', 'ADJ', 'NOUN', None, 'positive', negations['phraseStemmed'])
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, 'negations', 'priorpolarity', 'ADJ', 'NOUN', None, 'positive', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'positive')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'positive')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'positive')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'positive')
    
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'negative')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'negative')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'negative')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'negative')
    
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'neutral')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'neutral')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'neutral')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_adverb_tags, noun_tags, None, 'neutral')

    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_tags, noun_tags, None, 'positive')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_tags, noun_tags, None, 'positive')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_tags, noun_tags, None, 'positive')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_tags, noun_tags, None, 'positive')
    
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_tags, noun_tags, None, 'negative')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_tags, noun_tags, None, 'negative')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_tags, noun_tags, None, 'negative')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_tags, noun_tags, None, 'negative')
    
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'priorpolarity', adjective_tags, noun_tags, None, 'neutral')
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'priorpolarity', adjective_tags, noun_tags, None, 'neutral')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'priorpolarity', adjective_tags, noun_tags, None, 'neutral')
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'priorpolarity', adjective_tags, noun_tags, None, 'neutral')
    
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, 'negations', 'priorpolarity', adjective_tags, noun_tags, None, 'positive', negations['phraseStemmed'])
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, 'negations', 'priorpolarity', adjective_tags, noun_tags, None, 'positive', negations['phraseStemmed'])
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, 'negations', 'priorpolarity', adjective_tags, noun_tags, None, 'positive', negations['phraseStemmed'])
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, 'negations', 'priorpolarity', adjective_tags, noun_tags, None, 'positive', negations['phraseStemmed'])

    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 4, None, 'hostile', adjective_tags, noun_tags, None, None)
    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 5, None, 'hostile', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 6, None, 'hostile', adjective_tags, noun_tags, None, None)
#    df, colArr = countOneBeforeOtherNgramPosDf(colArr, df, 7, None, 'hostile', adjective_tags, noun_tags, None, None)
    return df, colArr

In [70]:
tStart = time.time()
selectedPolarizedSentencesMpqa, featureColumnsMpqa = calculateBeforeAfterNgramsPos(selectedPolarizedSentencesMpqa, featureColumnsMpqa)
tEnd = time.time()
print("Timed MPQA: {}".format(str(tEnd-tStart)))

['JJ', 'JJR', 'JJS', 'RB', 'RBR', 'RBS']
Timed(pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSpositiv): 2.89300012589
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSpositiv): 3.47799992561
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive): 2.92499995232
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive): 3.35699987411
Timed(pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSstrong): 2.81399989128
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSstrong): 3.5
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSnegativ): 3.83200001717
Timed(pos_ngram_4_A.D.JN.O.U.Nnegationspriorpolaritypositive): 0.319999933243
Timed(pos_ngram_5_A.D.JN.O.U.Nnegationspriorpolaritypositive): 0.332999944687
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive): 3.01300001144
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive): 3.62800002098
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative): 3.65100002289
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative): 3.77300000191
Timed(pos_ngr

In [71]:
if not onlyMpqa:
    tStart = time.time()
    sentencesTestSubsetImdb, featureColumnsImdb = calculateBeforeAfterNgramsPos(sentencesTestSubsetImdb, featureColumnsImdb)
    tEnd = time.time()
    print("Timed IMDB: {}".format(str(tEnd-tStart)))

['JJ', 'JJR', 'JJS', 'RB', 'RBR', 'RBS']
Timed(pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSpositiv): 4.36800003052
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSpositiv): 4.53200006485
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive): 4.65699982643
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive): 4.40100002289
Timed(pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSstrong): 4.41299986839
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSstrong): 4.41499996185
Timed(pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSnegativ): 4.40699982643
Timed(pos_ngram_4_A.D.JN.O.U.Nnegationspriorpolaritypositive): 4.5529999733
Timed(pos_ngram_5_A.D.JN.O.U.Nnegationspriorpolaritypositive): 4.84999990463
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive): 6.28699994087
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive): 6.70900011063
Timed(pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative): 6.0119998455
Timed(pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative): 5.16599988937
Timed(p

In [72]:
def generate_description_features(df, features):
    df_pos = df[df['sentiment-intensity'] > 0]
    df_neg = df[df['sentiment-intensity'] < 0]
    df_neu = df[df['sentiment-intensity'] == 0]
    total_counts = [df_pos.shape[0], df_neg.shape[0], df_neu.shape[0]]
    stats = []
    for feature in features.keys():
        if feature not in df.columns:
            continue
        # val1 = # of sentences with 0 val
        # val2 = # of sentences with other val
        # val3 = # of different features
        pos_stats = []
        neg_stats = []
        neutral_stats = []
        if df[feature].dtype == 'bool':
            pos_stats = [
                df_pos[df_pos[feature] == False].shape[0],
                df_pos[df_pos[feature] == True].shape[0],
                2
            ]
            neg_stats = [
                df_neg[df_neg[feature] == False].shape[0],
                df_neg[df_neg[feature] == True].shape[0],
                2
            ]
            neutral_stats = [
                df_neu[df_neu[feature] == False].shape[0],
                df_neu[df_neu[feature] == True].shape[0],
                2
            ]
        else: # counts
            pos_stats = [
                df_pos[df_pos[feature] == 0].shape[0],
                df_pos[df_pos[feature] > 0].shape[0],
                df_pos[feature].value_counts().shape[0]
            ]
            neg_stats = [
                df_neg[df_neg[feature]  == 0].shape[0],
                df_neg[df_neg[feature] > 0].shape[0],
                df_neg[feature].value_counts().shape[0]
            ]
            neutral_stats = [
                df_neu[df_neu[feature]  == 0].shape[0],
                df_neu[df_neu[feature] > 0 ].shape[0],
                df_neu[feature].value_counts().shape[0]
            ]
        
        row = [feature] + pos_stats + neg_stats + neutral_stats + total_counts
        stats.append(row)
        
    return pd.DataFrame(stats, columns = ['feature', 'pos=0', 'pos>1', 'pos-features',
                                                     'neg=0', 'neg>1', 'neg-features'
                                                     , 'neutral=0', 'neutral>1', 'neutral-features',
                                                     'total-pos', 'total-neg', 'total-neutral'])

In [73]:
stats = generate_description_features(selectedPolarizedSentencesMpqa, featureColumnsMpqa)
stats.shape

(135, 13)

In [74]:
stats.to_csv('./corpora/processed/df_stats.csv')

In [75]:
selectedPolarizedSentencesMpqa['pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSpositiv'].value_counts().shape

(7L,)

In [76]:
if not onlyMpqa:
    sentencesTestSubsetImdb[sentencesTestSubsetImdb['moreNegativeThanNeutral'] == True].shape

In [77]:
selected_columns = [
        'negations', 'positivCount', 'negativCount',
        'priorpolaritynegativeAfter',
        'priorpolaritypositiveBefore',
        'activeBefore', 'passiveBefore',
        'priorpolaritynegativeBefore',
        'hostileBefore', 'negativCountstrongsubj',
        'priorpolaritynegativeCountBefore', 'priorpolaritypositiveCountBefore',
        'morePositiveThanNegativeStrong', 'morePositiveThanNegativeWeak', 'morePositiveThanNegative',
        'priorpolaritypositiveAfter',
        'priorpolarityCountpositive', 'priorpolarityCountpositiveweaksubj',
        'priorpolarityCountpositivestrongsubj',
        'strongCount', 'passiveCount', 'activeCountweaksubj',
        'priorpolarityCountnegativestrongsubj', 'priorpolarityCountnegativeweaksubj',
'ngram_4_negativpriorpolaritynegative',
'ngram_4_negativpriorpolaritypositive',
'ngram_3_negativpriorpolaritynegative',
'ngram_3_negativpriorpolaritypositive',
'ngram_4_hostilepriorpolaritynegative',
'ngram_3_activepriorpolaritypositive',
'ngram_4_negativpriorpolaritypositive',
'pos_ngram_7_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative',
'pos_ngram_7_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive',    
'pos_ngram_6_JJ.JJR.JJSNN.NNP.NNSpriorpolaritypositive',
'pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive',
'pos_ngram_6_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive',
'pos_ngram_6_JJ.JJR.JJSNN.NNP.NNSpriorpolaritynegative',
'pos_ngram_7_JJ.JJR.JJSNN.NNP.NNSstrong',
'pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative',
#'pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritypositive',
#'pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolaritynegative',
#'pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpriorpolarityneutral',
#'pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSpositiv',
'ngram_4_negativpriorpolaritynegative',   
#'pos_ngram_6_JJ.JJR.JJSNN.NNP.NNSstrong',
#'pos_ngram_4_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive',
#'pos_ngram_6_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSactive',
        'priorpolaritypositiveCountAfter', 'priorpolaritynegativeCountAfter',
        'morePositiveThanNeutral', 'moreNegativeThanNeutral',
        'priorpolarityCountneutral', 'priorpolarityCountneutralstrongsubj',
        'priorpolarityCountneutralweaksubj',
        'priorpolarityneutralAfter',  'priorpolarityneutralBefore',
    
        'Allweaksubj', 'Allstrongsubj', 'activeCount',
        'strongCountweaksubj', 'positivCountweaksubj', 'positivCountstrongsubj'
    ]

selected_columns_train = selected_columns + ['sentiment-intensity']

print("Number of features: {}".format(len(selected_columns)))

Number of features: 55


In [85]:
def precalculate_feature_selection(className, stats):
    more1 = stats[className+'>1'].astype(float)    
    stats[stats[className+'-features'] == 0] = 1.00001
    stats[className+'-ratio'] = more1 / stats[className+'-features']
    stats[className+'-portion'] = more1 / stats['total-'+className] 
    return stats
    

def feature_selection(className, stats, ratio = None, portion = None, otherRatio = None):
    other = None
    if className == 'pos':
        other = ['neg', 'neutral']
    elif className == 'neg':
        other = ['pos', 'neutral']
    else:
        other = ['neg', 'pos']
    
    idx = None
    if ratio is not None:
        idx = stats[className+'-ratio'] > ratio
    if portion is not None:
        if idx is None:
            idx = stats[className+'-portion'] > portion
        else:
            idx = idx & (stats[className+'-portion'] > portion)

    if otherRatio is not None:
        idx2 = None
        idx2 = (stats[other[0]+'-ratio'] > otherRatio) | (stats[other[1]+'-ratio'] > otherRatio)

        if idx is None:
            idx = idx2
        else:
            idx = idx & idx2        

    return stats.loc[ idx, 'feature'].values

In [86]:
stats

feature  pos=0  pos>1  \
0               ngram_2_negationspriorpolaritypositive    644      0   
1                                 negativCountweaksubj    544    100   
2                    ngram_3_weakpriorpolaritynegative    636      8   
3                                          negateAfter    642      2   
4                               positivCountstrongsubj    484    160   
5                                         passiveAfter    614     30   
6                                  activeCountweaksubj    539    105   
7    pos_ngram_4_A.D.JN.O.U.Nnegationspriorpolarity...    644      0   
8                          priorpolaritybothCountAfter    644      0   
9                 ngram_4_negativpriorpolaritypositive    585     59   
10                                positivCountweaksubj    466    178   
11                                        noCountAfter    641      3   
12                    priorpolarityCountbothstrongsubj    644      0   
13                                         activeAfter    609     35   
14                   ngram_2_weakpriorpolaritynegative    640      4   
15                          priorpolarityCountnegative    527    117   
16                                       noCountBefore    643      1   
17                                         strongCount    430    214   
18                 ngram_2_activepriorpolaritypositive    607     37   
19                             priorpolaritybothBefore    644      0   
20                                           negations    565     79   
21                          priorpolarityCountpositive    341    303   
22                priorpolarityCountnegativestrongsubj    609     35   
23                        morePositiveThanNegativeWeak    477    167   
24   pos_ngram_5_A.D.JN.O.U.Nnegationspriorpolarity...    644      0   
25                             moreNegativeThanNeutral    542    102   
26                ngram_2_negativpriorpolaritynegative    626     18   
27                                        hostileCount    582     62   
28   pos_ngram_5_JJ.JJR.JJSNN.NNP.NNSpriorpolarityn...    641      3   
29   pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpri...    638      6   
..                                                 ...    ...    ...   
105               ngram_4_hostilepriorpolaritynegative    625     19   
106                             negativCountstrongsubj    612     32   
107                                            noAfter    641      3   
108                                        punctuation      0    644   
109                    priorpolaritynegativeCountAfter    604     40   
110                        priorpolaritynegativeBefore    608     36   
111                          priorpolarityneutralAfter    625     19   
112                ngram_4_negativpriorpolarityneutral    624     20   
113               ngram_3_hostilepriorpolaritynegative    629     15   
114                         priorpolaritypositiveAfter    592     52   
115                         priorpolaritynegativeAfter    604     40   
116                   priorpolaritynegativeCountBefore    608     36   
117                             priorpolarityCountboth    638      6   
118              ngram_3_negationspriorpolarityneutral    644      0   
119            pos_ngram_5_JJ.JJR.JJSNN.NNP.NNShostile    640      4   
120                                 hostileCountBefore    630     14   
121                ngram_2_negativpriorpolarityneutral    635      9   
122               ngram_4_negativpriorpolaritynegative    603     41   
123  pos_ngram_4_JJ.JJR.JJSNN.NNP.NNSpriorpolarityn...    641      3   
124             ngram_2_negationspriorpolaritynegative    644      0   
125  pos_ngram_5_JJ.JJR.JJS.RB.RBR.RBSNN.NNP.NNSpri...    640      4   
126             ngram_4_negationspriorpolaritypositive    644      0   
127                                           yesAfter    640      4   
128               ngram_2_persistpriorpolaritypositive    642      2   
129  pos_ngram_

In [87]:
stats = precalculate_feature_selection( 'pos', stats)
stats = precalculate_feature_selection( 'neg', stats)
stats = precalculate_feature_selection( 'neutral', stats)

In [147]:
def analyzeErrors(df, predicted, expected):
    print("Accuracy: {}".format(calculateAccuracy(df, predicted, expected)))
    print("Accuracy in positive sentiment: {}".format(calculateAccuracy(df[df[expected] == sentiment_positive], predicted, expected)))
    print("Accuracy in negative sentiment: {}".format(calculateAccuracy(df[df[expected] == sentiment_negative], predicted, expected)))
    print("Accuracy in neutral sentiment: {}".format(calculateAccuracy(df[df[expected] == 0], predicted, expected))) 
    cm = confusion_matrix(df[expected], df[predicted])
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
    print(cm)
    print(cm_normalized)


def calculateAccuracy(df, predicted, expected):
    if df.shape[0] == 0:
        return 0
    else:
        return df[df[predicted] == df[expected]].shape[0] / float(df.shape[0])

In [148]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, recall_score, precision_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.externals import joblib
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [149]:
def create_n_stratified_parts(df, n_cuts, project_columns):
    copy_df = df[project_columns].copy().reset_index()
    
    copy_df = copy_df.reindex(np.random.permutation(copy_df.index))
    positive = copy_df[copy_df['sentiment-intensity'] == sentiment_positive].reset_index(drop = True)
    neutral = copy_df[copy_df['sentiment-intensity'] == 0].reset_index(drop = True)
    negative = copy_df[copy_df['sentiment-intensity'] == sentiment_negative].reset_index(drop = True)
    
    positive_parts = []
    negative_parts = []
    neutral_parts = []
    positive_step = positive.shape[0] / n_cuts
    negative_step = negative.shape[0] / n_cuts
    neutral_step = neutral.shape[0] / n_cuts
    for part in range(n_cuts):
        if part == n_cuts - 1:
            positive_parts.append(positive[part * positive_step:])
            negative_parts.append(negative[part * negative_step:])
            neutral_parts.append(neutral[part * neutral_step:])
        else:
            positive_parts.append(positive[part * positive_step : (part+1) * positive_step])
            negative_parts.append(negative[part * negative_step : (part+1) * negative_step])
            neutral_parts.append(neutral[part * neutral_step : (part+1) * neutral_step])
            
    
    return positive_parts, negative_parts, neutral_parts

In [150]:
def create_n_stratified_neutral_parts(df, n_cuts, project_columns):
    copy_df = df[project_columns].copy().reset_index()
    
    copy_df = copy_df.reindex(np.random.permutation(copy_df.index))
    neutral = copy_df[copy_df['sentiment-neutral'] == 1].reset_index(drop = True)
    other = copy_df[copy_df['sentiment-neutral'] == 0].reset_index(drop = True)
    
    other_parts = []
    neutral_parts = []
    other_step = other.shape[0] / n_cuts
    neutral_step = neutral.shape[0] / n_cuts
    for part in range(n_cuts):
        if part == n_cuts - 1:
            other_parts.append(other[part * other_step:])
            neutral_parts.append(neutral[part * neutral_step:])
        else:
            other_parts.append(other[part * other_step : (part+1) * other_step])
            neutral_parts.append(neutral[part * neutral_step : (part+1) * neutral_step])
            
    return other_parts, neutral_parts

In [198]:
n_cuts = 9

In [392]:
pos_features = feature_selection('pos', stats, 1.1)
neg_features = feature_selection('neg', stats, 3.5, None, 4.0)
neutral_features = feature_selection('neutral', stats, 1.5, 0.05)
selected_columns_test = [] + pos_features.tolist() + neg_features.tolist() + neutral_features.tolist()
selected_columns_test = list(set(selected_columns_test))
selected_columns_train = selected_columns_test  + ['sentiment-intensity']
print("Number of features: pos = {}, neg = {}, neutral = {}, total = {}".format(len(pos_features), len(neg_features), len(neutral_features), len(selected_columns_train)))

Number of features: pos = 105, neg = 70, neutral = 45, total = 106


In [393]:
positive_mixed_parts, negative_mixed_parts, neutral_mixed_parts = create_n_stratified_parts(selectedPolarizedSentencesMpqa, n_cuts, selected_columns_train)

In [ ]:
best_test = None
best_train = None
best_predicted = None
best_accuracy = 0
best_clasifier = None

worst_accurracy = 1
worst_test = None
worst_predicted = None
classifier = None

accuracy = []
num_repeats = 2
consts = [4, 5, 6, 7, 8, 10, 12, 15]
#consts = [8]

for idx_const in range(len(consts)):
    print("######### Next Constant")
    for part in range(n_cuts):
        test = pd.DataFrame({})
        train = pd.DataFrame({})
        # create test and training set
        for idx in range(n_cuts):
            if idx == part:
                test = pd.concat([positive_mixed_parts[idx], negative_mixed_parts[idx], neutral_mixed_parts[idx]])
            else:
                train = pd.concat([train, positive_mixed_parts[idx], negative_mixed_parts[idx], neutral_mixed_parts[idx]])

        train.reset_index(inplace = True, drop = True)
        train = train.reindex(np.random.permutation(train.index))
        # train & evaluate
        train_results = train['sentiment-intensity'].values
        train.drop('sentiment-intensity', axis = 1, inplace = True)
        train_index = train['index'].values
        train.drop('index', axis = 1, inplace = True)    
        test_results = test['sentiment-intensity'].values
        test.drop('sentiment-intensity', axis = 1, inplace = True)
        test_index = test['index'].values
        test.drop('index', axis = 1, inplace = True)    
        acc = []
        for repeat_test in range(num_repeats):
            clasifier = RandomForestClassifier(n_estimators = 300, max_features = 'log2',
                                                max_depth = consts[idx_const], n_jobs = -1)
#            clasifier = ExtraTreesClassifier(n_estimators = consts[idx_const], max_features = 'sqrt',
#                                                max_depth = 7, n_jobs = -1)

#            clasifier = AdaBoostClassifier( ExtraTreesClassifier(n_estimators = consts[idx_const], max_features = 'sqrt',
#                                                max_depth = 7, n_jobs = -1),
#                                                n_estimators=consts[idx_const],
#                                                learning_rate=1.8)

#            clasifier = AdaBoostClassifier( DecisionTreeClassifier(max_depth=6),
#                                                n_estimators=consts[idx_const],
#                                                learning_rate=1.8)
            clasifier.fit(train.values, train_results)

            predicted = clasifier.predict(test.values)
            #current_score = clasifier.score(train.values, train_results)
            current_score = recall_score(test_results, predicted, average = None)
            list_predicted = list(predicted)
            current_accuracy = accuracy_score(test_results, predicted)
            acc.append(current_accuracy)
            print("idx = {}, round = {}, cut = {}, accuracy = {} ------------- score = {}".format(idx_const, repeat_test, part, current_accuracy, current_score))
            
            if worst_accurracy > current_accuracy:
                worst_accurracy = current_accuracy
                worst_test = test.copy()
                worst_test['index'] = test_index
                worst_test['sentiment-intensity'] = test_results
                worst_test['predicted'] = predicted
                print("@@@ Worst Configuration: idx = {}, round = {}, cut = {}, accuracy = {}".format(idx_const, repeat_test, part, current_accuracy))
            
            if best_accuracy < current_accuracy:
                best_test = test.copy()
                best_test['index'] = test_index
                best_test['sentiment-intensity'] = test_results
                best_test['predicted'] = predicted
                best_train = train.copy()
                best_train['index'] = train_index
                best_train['sentiment-intensity'] = train_results
                best_predicted = predicted.copy()
                best_clasifier = clasifier
                best_accuracy = current_accuracy
                print("@@@ Best Configuration: idx = {}, round = {}, cut = {}, accuracy = {}".format(idx_const, repeat_test, part, current_accuracy))

        accuracy.append(np.mean(acc))


    print("{}) Mean Accuracy: {}".format(consts[idx_const], np.mean(accuracy)))

######### Next Constant
idx = 0, round = 0, cut = 0, accuracy = 0.413145539906 ------------- score = [ 0.38028169  0.52112676  0.33802817]
@@@ Worst Configuration: idx = 0, round = 0, cut = 0, accuracy = 0.413145539906
@@@ Best Configuration: idx = 0, round = 0, cut = 0, accuracy = 0.413145539906
idx = 0, round = 1, cut = 0, accuracy = 0.422535211268 ------------- score = [ 0.4084507   0.52112676  0.33802817]
@@@ Best Configuration: idx = 0, round = 1, cut = 0, accuracy = 0.422535211268
idx = 0, round = 0, cut = 1, accuracy = 0.544600938967 ------------- score = [ 0.63380282  0.5915493   0.4084507 ]
@@@ Best Configuration: idx = 0, round = 0, cut = 1, accuracy = 0.544600938967
idx = 0, round = 1, cut = 1, accuracy = 0.558685446009 ------------- score = [ 0.64788732  0.6056338   0.42253521]
@@@ Best Configuration: idx = 0, round = 1, cut = 1, accuracy = 0.558685446009
idx = 0, round = 0, cut = 2, accuracy = 0.50234741784 ------------- score = [ 0.47887324  0.50704225  0.52112676]
idx = 

In [324]:
#best_test['predicted'] = best_predicted
analyzeErrors(best_test, 'predicted', 'sentiment-intensity')

Accuracy: 0.568075117371
Accuracy in positive sentiment: 0.535211267606
Accuracy in negative sentiment: 0.549295774648
Accuracy in neutral sentiment: 0.619718309859
[[39 18 14]
 [14 44 13]
 [ 7 26 38]]
[[ 0.54929577  0.25352113  0.1971831 ]
 [ 0.1971831   0.61971831  0.18309859]
 [ 0.09859155  0.36619718  0.53521127]]


In [398]:
analyzeErrors(best_test, 'predicted', 'sentiment-intensity')

Accuracy: 0.586854460094
Accuracy in positive sentiment: 0.450704225352
Accuracy in negative sentiment: 0.676056338028
Accuracy in neutral sentiment: 0.633802816901
[[48 21  2]
 [14 45 12]
 [17 22 32]]
[[ 0.67605634  0.29577465  0.02816901]
 [ 0.1971831   0.63380282  0.16901408]
 [ 0.23943662  0.30985915  0.45070423]]


In [396]:
#best_test['predicted'] = best_predicted
analyzeErrors(worst_test, 'predicted', 'sentiment-intensity')

Accuracy: 0.412280701754
Accuracy in positive sentiment: 0.276315789474
Accuracy in negative sentiment: 0.421052631579
Accuracy in neutral sentiment: 0.539473684211
[[32 28 16]
 [17 41 18]
 [17 38 21]]
[[ 0.42105263  0.36842105  0.21052632]
 [ 0.22368421  0.53947368  0.23684211]
 [ 0.22368421  0.5         0.27631579]]


In [103]:
analyzeErrors(worst_test, 'predicted', 'sentiment-intensity')

Accuracy: 0.385416666667
Accuracy in positive sentiment: 0.359375
Accuracy in negative sentiment: 0.296875
Accuracy in neutral sentiment: 0.5
[[19 32 13]
 [11 32 21]
 [14 27 23]]
[[ 0.296875  0.5       0.203125]
 [ 0.171875  0.5       0.328125]
 [ 0.21875   0.421875  0.359375]]


In [ ]:
selected_columns_neutral = [
        'negations',
#        'wordCount', 
        'positivCount',
        'negativCount',
#        'priorpolaritynegativeAfter',
        'priorpolaritypositiveBefore',
        'activeBefore', 'passiveBefore',
#        'priorpolaritynegativeBefore',
#        'hostileBefore', 'yesBefore', 'yesAfter', 'noBefore', 'negateBefore',
 #       'activeCountBefore','passiveCountBefore', 'hostileCountBefore', 'yesCountBefore',
#        'noCountBefore', 'negateCountBefore', 'negateCountAfter', 
        #'activeAfter',  'passiveAfter',
        'priorpolaritynegativeCountBefore', 'priorpolaritypositiveCountBefore',
#        'activeCountAfter', 'passiveCountAfter', 'hostileCountAfter', 
        'morePositiveThanNegativeStrong', 'morePositiveThanNegativeWeak', 'morePositiveThanNegative',
#       'yesCountAfter', 'noCountAfter', 
        'priorpolaritynegativeCountAfter',
#        'priorpolaritypositiveAfter',
#        'negateAfter',
#        'strongCount',
        'priorpolaritypositiveCountAfter',
#        'hostileAfter', 'noAfter',
        'morePositiveThanNeutral', 'moreNegativeThanNeutral',
        'priorpolarityCountneutral', 'priorpolarityCountneutralstrongsubj',
#        'priorpolarityCountbothstrongsubj', 'priorpolarityCountbothweaksubj',
        'priorpolarityCountneutralweaksubj',
        'priorpolarityneutralAfter',  'priorpolarityneutralBefore'
#        'priorpolaritybothBefore', 'priorpolaritybothAfter'
    ]

selected_columns_train_neutral = selected_columns_neutral + ['sentiment-neutral']
n_cuts_neutrals = 6
print("Number of features: {}".format(len(selected_columns_neutral)))

In [ ]:
other_parts, neutral_parts = create_n_stratified_neutral_parts(neutralSelectedSentencesMpqa, n_cuts_neutrals, selected_columns_train_neutral)

In [ ]:
best_test = None
best_train = None
best_predicted = None
best_accuracy = 0
best_clasifier = None

accuracy = []
num_repeats = 2
consts = [4, 5, 6, 7, 8, 9]
#consts = [8]

for idx_const in range(len(consts)):
    print("######### Next Constant")
    for part in range(n_cuts_neutrals):
        test = pd.DataFrame({})
        train = pd.DataFrame({})
        # create test and training set
        for idx in range(n_cuts_neutrals):
            if idx != part:
                test = pd.concat([other_parts[idx], neutral_parts[idx]])
            else:
                train = pd.concat([train, other_parts[idx], neutral_parts[idx]])

        train.reset_index(inplace = True, drop = True)
        train = train.reindex(np.random.permutation(train.index))
        # train & evaluate
        train_results = train['sentiment-neutral'].values
        train.drop('sentiment-neutral', axis = 1, inplace = True)
        train_index = train['index'].values
        train.drop('index', axis = 1, inplace = True)    
        test_results = test['sentiment-neutral'].values
        test.drop('sentiment-neutral', axis = 1, inplace = True)
        test_index = test['index'].values
        test.drop('index', axis = 1, inplace = True)    
        acc = []
        for repeat_test in range(num_repeats):
            clasifier = RandomForestClassifier(n_estimators = 100, max_features = 'log2',
                                                max_depth = consts[idx_const], n_jobs = -1)

#            clasifier = AdaBoostClassifier( ExtraTreesClassifier(n_estimators = consts[idx_const], max_features = 'sqrt',
#                                                max_depth = 7, n_jobs = -1),
#                                                n_estimators=consts[idx_const],
#                                                learning_rate=1.8)

#            clasifier = AdaBoostClassifier( DecisionTreeClassifier(max_depth=6),
#                                                n_estimators=consts[idx_const],
#                                                learning_rate=1.8)
            clasifier.fit(train.values, train_results)
            current_score = clasifier.score(train.values, train_results)
            predicted = clasifier.predict(test.values)
            list_predicted = list(predicted)
            current_f1_score = f1_score(test_results, predicted)
            current_accuracy = accuracy_score(test_results, predicted)
            acc.append(current_accuracy)
            print("idx = {}, round = {}, cut = {}, accuracy = {}, train score = {}, f1 score = {}"
                          .format(idx_const, repeat_test, part, current_accuracy, current_score, current_f1_score))

            if best_accuracy < current_score:
                best_test = test.copy()
                best_test['index'] = test_index
                best_test['sentiment-neutral'] = test_results
                best_test['predicted'] = predicted
                best_train = train.copy()
                best_train['index'] = train_index
                best_train['sentiment-neutral'] = train_results
                best_predicted = predicted.copy()
                best_clasifier = clasifier
                best_accuracy = current_score
                print("@@@ Best Configuration: idx = {}, round = {}, cut = {}, accuracy = {}".format(idx_const, repeat_test, part, current_accuracy))

        accuracy.append(np.mean(acc))


    print("{}) Mean Accuracy: {}".format(consts[idx_const], np.mean(accuracy)))

In [203]:
best_test['predicted'] = best_predicted
analyzeErrors(best_test, 'predicted', 'sentiment-neutral')

KeyError: 'sentiment-neutral'

In [ ]:
wrong_sentences = neutralSelectedSentencesMpqa.loc[best_test.loc[best_test['predicted'] != best_test['sentiment-neutral'], 'index'], neutralSelectedSentencesMpqa.columns]

In [204]:
# verification phase
def directClassification(row, pos_column, neg_column, suffix):
    if row[pos_column] < row[neg_column]:
        row['apriori-class-'+suffix] = -1
    elif row[pos_column] > row[neg_column]:
        row['apriori-class-'+suffix] = 1
    else:
        row['apriori-class-'+suffix] = 0
    
    return row

In [215]:
doSave = True

In [397]:
if doSave:
    joblib.dump(best_clasifier, './models-sentiment/version_6/version_6.pkl')
    with open('./models-sentiment/version_6/features.dump','wb') as fp:
        pickle.dump(selected_columns_test, fp)    

In [205]:
def calculateSentiment(sentences, column_predicted):
    numPositive = sentences[sentences[column_predicted] == sentiment_positive].shape[0]
    numNegative = sentences[sentences[column_predicted] == sentiment_negative].shape[0]
    numNeutral = sentences[sentences[column_predicted] == 0].shape[0]
#    print("Pos = {}; Neg = {}; Neutral = {}".format(numPositive, numNegative, numNeutral))
    if numPositive > numNegative:
        return sentiment_positive
    elif numPositive < numNegative:
        return sentiment_negative
    else:
        return 0    

def calculateSentimentReview(review_id, df, col):
    review_data = review_id.split('#')
    review_set_id = int(review_data[2])
    review_rating = int(review_data[1])
    review_df_id = int(review_data[0])
    sentences = df[(df['id'] == review_df_id) & (df['set'] == review_set_id) & (df['rating'] == review_rating) ]
    return calculateSentiment(sentences, col)

In [206]:
test_reviews_even['expected'] = test_reviews_even['type']
verificationData = sentencesTestSubsetImdb[list(set([] + pos_features.tolist() + neg_features.tolist() + neutral_features.tolist()))]

In [400]:
sentencesTestSubsetImdb['trained-classifier-predicted'] = best_clasifier.predict(verificationData.values)

In [401]:
test_reviews_even['predicted-model'] = test_reviews_even['real-id'].map(lambda cell: calculateSentimentReview(cell, sentencesTestSubsetImdb, 'trained-classifier-predicted'))
print("Done")

Done


In [209]:
sentencesTestSubsetImdb = sentencesTestSubsetImdb.apply(lambda row: directClassification(row, 'priorpolarityCountpositive', 'priorpolarityCountnegative', 'direct' ), axis = 1)
test_reviews_even['predicted-direct'] = test_reviews_even['real-id'].map(lambda cell: calculateSentimentReview(cell, sentencesTestSubsetImdb, 'apriori-class-direct'))
print("Done")
selectedPolarizedSentencesMpqa = selectedPolarizedSentencesMpqa.apply(lambda row: directClassification(row, 'priorpolarityCountpositive', 'priorpolarityCountnegative', 'direct' ), axis = 1)

Done


In [402]:
print("Direct model: {}".format(calculateAccuracy(test_reviews_even, 'predicted-direct', 'expected')))
print("Trained model: {}".format(calculateAccuracy(test_reviews_even, 'predicted-model', 'expected')))
print("")
print("Direct model (sentences): {}".format(calculateAccuracy(selectedPolarizedSentencesMpqa, 'apriori-class-direct', 'sentiment-intensity')))

Direct model: 0.510016025641
Trained model: 0.535657051282

Direct model (sentences): 0.435300207039


In [403]:
print("Direct model")
analyzeErrors(test_reviews_even, 'predicted-direct', 'expected')
print
print("Trained model")
analyzeErrors(test_reviews_even, 'predicted-model', 'expected')


Direct model
Accuracy: 0.510016025641
Accuracy in positive sentiment: 0.799679487179
Accuracy in negative sentiment: 0.220352564103
Accuracy in neutral sentiment: 0
[[275 171 802]
 [  0   0   0]
 [121 129 998]]
[[ 0.22035256  0.13701923  0.64262821]
 [        nan         nan         nan]
 [ 0.09695513  0.10336538  0.79967949]]

Trained model
Accuracy: 0.535657051282
Accuracy in positive sentiment: 0.274038461538
Accuracy in negative sentiment: 0.797275641026
Accuracy in neutral sentiment: 0
[[995 134 119]
 [  0   0   0]
 [716 190 342]]
[[ 0.79727564  0.10737179  0.09535256]
 [        nan         nan         nan]
 [ 0.57371795  0.15224359  0.27403846]]


In [381]:
# Neural network
from tools.thirdparty.nnbook import network2

In [382]:
def preprocessResultsNN(row):
    if row['expected'] > 0:
        row['pos'] = 1
        row['neuron'] = 2
    elif row['expected'] < 0:
        row['neg'] = 1
        row['neuron'] = 0
    else:
        row['neutral'] = 1
        row['neuron'] = 1
    
    return row

def preprocessDataFrameForNN(df, not_test = True):
    df_nn = df.drop('index', axis = 1).reset_index(drop = True)
    expected_dt = pd.DataFrame(np.zeros((df_nn.shape[0], 5)), columns = ['neg', 'neutral', 'pos', 'neuron', 'expected'])
    expected_dt['expected'] = df_nn['sentiment-intensity']
    expected_dt = expected_dt.apply(lambda row: preprocessResultsNN(row), axis = 1)
    df_nn.drop('sentiment-intensity', axis = 1, inplace = True)
    if 'predicted' in df_nn.columns:
        df_nn.drop('predicted', axis = 1, inplace = True)

    inp_size = len(df_nn.columns)
    out_size = 3
    
    for col in df_nn.columns:
        if df_nn[col].dtype == 'bool':
            df_nn[col] = df_nn[col].astype(int)

    res = expected_dt[['neg', 'neutral', 'pos']].values
    if not_test == False:
        res = expected_dt['neuron'].values
        out_size = 1
            
        training_data = [(np.ndarray((inp_size,1), buffer=np.array(x)),
                        np.ndarray((out_size,1), buffer=np.array(y), dtype=int))
                        for (x,y) in zip(df_nn.values, res)]
    else:
        training_data = [(np.ndarray((inp_size,1), buffer=np.array(x)),
                        np.ndarray((out_size,1), buffer=np.array(y), dtype=int))
                        for (x,y) in zip(df_nn.values, res)]

    return training_data, df_nn

In [383]:
pos_test = best_train[best_train['sentiment-intensity'] == sentiment_positive][1:5]
neg_test = best_train[best_train['sentiment-intensity'] == sentiment_negative][1:5]
neutral_test = best_train[best_train['sentiment-intensity'] == 0][1:5]
train_test_data = pd.concat([pos_test, neg_test, neutral_test])
train_test_data.shape

(12, 107)

In [384]:
training_data, df_nn = preprocessDataFrameForNN(best_train)
test_data, df_nn_test = preprocessDataFrameForNN(best_test, False)

In [385]:
hidden_neurons = 30
nn = network2.Network([len(training_data[0][0]), hidden_neurons, 3],
                                cost=network2.CrossEntropyCost)
#nn.large_weight_initializer()

In [386]:
epochs = 3
lmbda = 0.00002
learningRate = 0.00002
batchSize = 3

nn.SGD(
#        experiment_data
        training_data
       , epochs,batchSize, learningRate,
        lmbda = lmbda, evaluation_data = test_data, 
           monitor_training_accuracy = True
       , monitor_evaluation_accuracy = True,
           monitor_evaluation_cost = True, monitor_training_cost = True
      )

Epoch 0 training complete
Cost on training data: 5.99231044954e+307
Accuracy on training data: 573 / 1719
Cost on evaluation data: 1.79769313486e+308
Accuracy on evaluation data: 0 / 213

Epoch 1 training complete
Cost on training data: 5.99231044954e+307
Accuracy on training data: 573 / 1719
Cost on evaluation data: 1.79769313486e+308
Accuracy on evaluation data: 0 / 213

Epoch 2 training complete
Cost on training data: 5.99231044954e+307
Accuracy on training data: 573 / 1719
Cost on evaluation data: 1.79769313486e+308
Accuracy on evaluation data: 0 / 213



([1.7976931348623093e+308, 1.7976931348623093e+308, 1.7976931348623093e+308],
 [0, 0, 0],
 [5.9923104495410088e+307, 5.9923104495410088e+307, 5.9923104495410088e+307],
 [573, 573, 573])

In [342]:
np.ndarray((len(df_nn.values[0]),), buffer=np.array(df_nn.values[0]))

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   1.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   1.,
         1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  46.,
         0.,   0.,   0.,   0.,   1.,   1.,   0.,   2.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.])

In [336]:
training_data[0]

(array([[  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        